spring:
  application:
    name: waver
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  datasource:
    url: jdbc:mysql://localhost:3306/waver
    username: root
    password: 12345
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/

springdoc:
  api-docs:
    path: /v3/api-docs        # OpenAPI JSON 경로
  swagger-ui:
    path: /swagger-ui         # Swagger UI 접속 경로
    disable-swagger-default-url: true  # 🧨 Petstore 제거
    url: /v3/api-docs         # 내 API 문서 명시

waver:
  secret:
    name: USER_ID
    key: "wH5pbJDmpvIKWy3k5CXHTIApJEb3M/EAT7EwSrBscJA="
    access-token-validity: 300d
  file:
    upload:
      path: /Users/temp/Desktop/workspace/waver_spring/upload
    images:
      path: http://localhost:8080/waver/image
    statics:
      path: http://localhost:8080/images

logging:
  level:
    root: info

