spring:
  application:
    name: waver
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  datasource:
    url: jdbc:mysql://localhost:3306/waver
    username: root
    password: 12345
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    url: /v3/api-docs
    disable-swagger-default-url: true

waver:
  secret:
    name: USER_ID
    key: "wH5pbJDmpvIKWy3k5CXHTIApJEb3M/EAT7EwSrBscJA="
    access-token-validity: 300d
  file:
    upload:
      # 로컬 경로에 맞게 수정 필요
      path: /Users/temp/Desktop/workspace/waver_spring/upload
    images:
      path: http://localhost:8080/waver/image
    statics:
      path: http://localhost:8080/images

logging:
  level:
    root: info

